export const BUSINESS_DOCUMENT_KINDS = [
  "BILLING_NOTE",
  "INVOICE",
  "QUOTATION",
  "RECEIPT",
] as const;

export const BUSINESS_DOCUMENT_KIND_ABBREVIATIONS = [
  "BL",
  "INV",
  "QT",
  "RE",
] as const;

export const BUSINESS_DOCUMENT_KIND_ABBREVIATIONS_MAP = {
  [BUSINESS_DOCUMENT_KINDS[0]]: BUSINESS_DOCUMENT_KIND_ABBREVIATIONS[0],
  [BUSINESS_DOCUMENT_KINDS[1]]: BUSINESS_DOCUMENT_KIND_ABBREVIATIONS[1],
  [BUSINESS_DOCUMENT_KINDS[2]]: BUSINESS_DOCUMENT_KIND_ABBREVIATIONS[2],
  [BUSINESS_DOCUMENT_KINDS[3]]: BUSINESS_DOCUMENT_KIND_ABBREVIATIONS[3],
} as const;

export const BUSINESS_DOCUMENT_STATUSES = [
  "PENDING",
  "ISSUED",
  "RECEIPT_CREATED",
  "PAID",
  "VOID",
  "REJECTED",
] as const;
