export const BUSINESS_DOCUMENT_KINDS = [
  "QUOTATION",
  "INVOICE",
  "BILLING_NOTE",
] as const;

export const BUSINESS_DOCUMENT_KIND_ABBREVIATIONS = [
  "QT",
  "INV",
  "BL",
] as const;

export const BUSINESS_DOCUMENT_KIND_ABBREVIATIONS_MAP = {
  [BUSINESS_DOCUMENT_KINDS[0]]: BUSINESS_DOCUMENT_KIND_ABBREVIATIONS[0],
  [BUSINESS_DOCUMENT_KINDS[1]]: BUSINESS_DOCUMENT_KIND_ABBREVIATIONS[1],
  [BUSINESS_DOCUMENT_KINDS[2]]: BUSINESS_DOCUMENT_KIND_ABBREVIATIONS[2],
} as const;
